export default [
  {
    id: 'OBCU5XAM',
    type: 'RectRoundSprite',
    props: {
      borderRadius: 30,
      stroke: '#9d9d9d',
      strokeWidth: 2,
      content:
        '<p><b style=""><font color="#ffffff">卡顿性能测试</font></b></p>',
      fill: '#9d9d9d',
    },
    attrs: {
      coordinate: {
        x: 348,
        y: 92.66092895214604,
      },
      size: {
        width: 136,
        height: 53,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: 'VH5ZBJ8B',
    type: 'ConnectLineSprite',
    props: {
      start: {
        x: 1,
        y: 170.58046447607302,
        port: {
          spriteId: 'XECA64VG',
          id: 'sprite-port__XECA64VG__0',
          index: 0,
          x: 50,
          y: 0,
          arcAngle: 270,
        },
      },
      end: {
        x: 0,
        y: 0,
        port: {
          spriteId: 'OBCU5XAM',
          id: 'sprite-port__OBCU5XAM__1',
          index: 1,
          x: 50,
          y: 100,
          arcAngle: 90,
        },
      },
      offset: 50,
      lineType: 'SmoothCurve',
      strokeWidth: 2,
      strokeDasharray: 'none',
      stroke: '#4e83fd',
    },
    attrs: {
      coordinate: {
        x: 416,
        y: 145.66092895214604,
      },
      size: {
        width: 1,
        height: 170.58046447607302,
      },
      angle: 0,
      style: {},
      creating: false,
    },
  },
  {
    id: 'EQF39ONY',
    type: 'ConnectLineSprite',
    props: {
      start: {
        x: 0,
        y: 302.5804644760731,
        port: {
          spriteId: 'XECA64VG',
          id: 'sprite-port__XECA64VG__3',
          index: 3,
          x: 100,
          y: 50,
          arcAngle: 0,
        },
      },
      end: {
        x: 21.5,
        y: 0,
        port: {
          spriteId: '4G4QRHE7',
          id: 'sprite-port__4G4QRHE7__2',
          index: 2,
          x: 0,
          y: 50,
          arcAngle: 180,
        },
      },
      offset: 50,
      lineType: 'SmoothCurve',
      strokeWidth: 2,
      strokeDasharray: 'none',
      stroke: '#4e83fd',
    },
    attrs: {
      coordinate: {
        x: 499.5,
        y: 44.16092895214601,
      },
      size: {
        width: 21.5,
        height: 302.5804644760731,
      },
      angle: 0,
      style: {},
      creating: false,
    },
  },
  {
    id: 'W58243LV',
    type: 'RectRoundSprite',
    props: {
      borderRadius: 30,
      stroke: '#9d9d9d',
      strokeWidth: 2,
      content: '<p>节点2<br/></p>',
    },
    attrs: {
      coordinate: {
        x: 676,
        y: 63.66092895214604,
      },
      size: {
        width: 136,
        height: 53,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: 'YSLW87EG',
    type: 'RectRoundSprite',
    props: {
      borderRadius: 30,
      stroke: '#9d9d9d',
      strokeWidth: 2,
      content: '<p>节点3<br/></p>',
    },
    attrs: {
      coordinate: {
        x: 794.5,
        y: 139.66092895214604,
      },
      size: {
        width: 136,
        height: 53,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: 'ERW9Z42O',
    type: 'RectRoundSprite',
    props: {
      borderRadius: 30,
      stroke: '#9d9d9d',
      strokeWidth: 2,
      content: '<p>节点4<br/></p>',
    },
    attrs: {
      coordinate: {
        x: 843.5,
        y: 222.74139342821906,
      },
      size: {
        width: 136,
        height: 53,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: '9S6ONM15',
    type: 'RectRoundSprite',
    props: {
      borderRadius: 30,
      stroke: '#9d9d9d',
      strokeWidth: 2,
      content: '<p>节点5<br/></p>',
    },
    attrs: {
      coordinate: {
        x: 828.5,
        y: 302.24139342821906,
      },
      size: {
        width: 136,
        height: 53,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: '4K2JBD0E',
    type: 'RectRoundSprite',
    props: {
      borderRadius: 30,
      stroke: '#9d9d9d',
      strokeWidth: 2,
      content: '<p>节点6<br/></p>',
    },
    attrs: {
      coordinate: {
        x: 794.5,
        y: 375.66092895214604,
      },
      size: {
        width: 136,
        height: 53,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: 'JS7SBZV4',
    type: 'ConnectLineSprite',
    props: {
      start: {
        x: 0,
        y: 256.580464476073,
        port: {
          spriteId: 'XECA64VG',
          id: 'sprite-port__XECA64VG__3',
          index: 3,
          x: 100,
          y: 50,
          arcAngle: 0,
        },
      },
      end: {
        x: 176.5,
        y: 0,
        port: {
          spriteId: 'W58243LV',
          id: 'sprite-port__W58243LV__2',
          index: 2,
          x: 0,
          y: 50,
          arcAngle: 180,
        },
      },
      offset: 50,
      lineType: 'SmoothCurve',
      strokeWidth: 2,
      strokeDasharray: 'none',
      stroke: '#4e83fd',
    },
    attrs: {
      coordinate: {
        x: 499.5,
        y: 90.16092895214604,
      },
      size: {
        width: 176.5,
        height: 256.580464476073,
      },
      angle: 0,
      style: {},
      creating: false,
    },
  },
  {
    id: 'SFUDCXT0',
    type: 'ConnectLineSprite',
    props: {
      start: {
        x: 0,
        y: 180.58046447607302,
        port: {
          spriteId: 'XECA64VG',
          id: 'sprite-port__XECA64VG__3',
          index: 3,
          x: 100,
          y: 50,
          arcAngle: 0,
        },
      },
      end: {
        x: 295,
        y: 0,
        port: {
          spriteId: 'YSLW87EG',
          id: 'sprite-port__YSLW87EG__2',
          index: 2,
          x: 0,
          y: 50,
          arcAngle: 180,
        },
      },
      offset: 50,
      lineType: 'SmoothCurve',
      strokeWidth: 2,
      strokeDasharray: 'none',
      stroke: '#4e83fd',
    },
    attrs: {
      coordinate: {
        x: 499.5,
        y: 166.16092895214604,
      },
      size: {
        width: 295,
        height: 180.58046447607302,
      },
      angle: 0,
      style: {},
      creating: false,
    },
  },
  {
    id: '3M22WLS6',
    type: 'ConnectLineSprite',
    props: {
      start: {
        x: 0,
        y: 97.5,
        port: {
          spriteId: 'XECA64VG',
          id: 'sprite-port__XECA64VG__3',
          index: 3,
          x: 100,
          y: 50,
          arcAngle: 0,
        },
      },
      end: {
        x: 344,
        y: 0,
        port: {
          spriteId: 'ERW9Z42O',
          id: 'sprite-port__ERW9Z42O__2',
          index: 2,
          x: 0,
          y: 50,
          arcAngle: 180,
        },
      },
      offset: 50,
      lineType: 'SmoothCurve',
      strokeWidth: 2,
      strokeDasharray: 'none',
      stroke: '#4e83fd',
    },
    attrs: {
      coordinate: {
        x: 499.5,
        y: 249.24139342821906,
      },
      size: {
        width: 344,
        height: 97.5,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: '1R7Z6WXM',
    type: 'RectRoundSprite',
    props: {
      borderRadius: 30,
      stroke: '#9d9d9d',
      strokeWidth: 2,
      content: '<p>节点7<br/></p>',
    },
    attrs: {
      coordinate: {
        x: 805.5,
        y: 471.66092895214604,
      },
      size: {
        width: 136,
        height: 53,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: 'UNDKTWCD',
    type: 'RectRoundSprite',
    props: {
      borderRadius: 30,
      stroke: '#9d9d9d',
      strokeWidth: 2,
      content: '<p>节点8<br/></p>',
    },
    attrs: {
      coordinate: {
        x: 748.5,
        y: 568.660928952146,
      },
      size: {
        width: 136,
        height: 53,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: 'NM6PI6JF',
    type: 'RectRoundSprite',
    props: {
      borderRadius: 30,
      stroke: '#9d9d9d',
      strokeWidth: 2,
      content: '<p>节点9<br/></p>',
    },
    attrs: {
      coordinate: {
        x: 551.5,
        y: 568.660928952146,
      },
      size: {
        width: 136,
        height: 53,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: 'MLY1WJU8',
    type: 'RectRoundSprite',
    props: {
      borderRadius: 30,
      stroke: '#9d9d9d',
      strokeWidth: 2,
      content: '<p>节点17<br/></p>',
    },
    attrs: {
      coordinate: {
        x: 172.5,
        y: 23.66092895214601,
      },
      size: {
        width: 136,
        height: 53,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: '2N0FLF16',
    type: 'RectRoundSprite',
    props: {
      borderRadius: 30,
      stroke: '#9d9d9d',
      strokeWidth: 2,
      content: '<p>节点16<br/></p>',
    },
    attrs: {
      coordinate: {
        x: 104.5,
        y: 105.66092895214601,
      },
      size: {
        width: 136,
        height: 53,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: 'U44I0I2W',
    type: 'RectRoundSprite',
    props: {
      borderRadius: 30,
      stroke: '#9d9d9d',
      strokeWidth: 2,
      content: '<p>节点15<br/></p>',
    },
    attrs: {
      coordinate: {
        x: 24.5,
        y: 187.66092895214604,
      },
      size: {
        width: 136,
        height: 53,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: 'RG4ISEB0',
    type: 'RectRoundSprite',
    props: {
      borderRadius: 30,
      stroke: '#9d9d9d',
      strokeWidth: 2,
      content: '<p>节点14<br/></p>',
    },
    attrs: {
      coordinate: {
        x: 25.5,
        y: 275.74139342821906,
      },
      size: {
        width: 136,
        height: 53,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: '7E06SLK0',
    type: 'ConnectLineSprite',
    props: {
      start: {
        x: 0,
        y: 18,
        port: {
          spriteId: 'XECA64VG',
          id: 'sprite-port__XECA64VG__3',
          index: 3,
          x: 100,
          y: 50,
          arcAngle: 0,
        },
      },
      end: {
        x: 329,
        y: 0,
        port: {
          spriteId: '9S6ONM15',
          id: 'sprite-port__9S6ONM15__2',
          index: 2,
          x: 0,
          y: 50,
          arcAngle: 180,
        },
      },
      offset: 50,
      lineType: 'SmoothCurve',
      strokeWidth: 2,
      strokeDasharray: 'none',
      stroke: '#4e83fd',
    },
    attrs: {
      coordinate: {
        x: 499.5,
        y: 328.74139342821906,
      },
      size: {
        width: 329,
        height: 18,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: 'P9QSZYFU',
    type: 'ConnectLineSprite',
    props: {
      start: {
        x: 0,
        y: 0,
        port: {
          spriteId: 'XECA64VG',
          id: 'sprite-port__XECA64VG__3',
          index: 3,
          x: 100,
          y: 50,
          arcAngle: 0,
        },
      },
      end: {
        x: 295,
        y: 55.41953552392698,
        port: {
          spriteId: '4K2JBD0E',
          id: 'sprite-port__4K2JBD0E__2',
          index: 2,
          x: 0,
          y: 50,
          arcAngle: 180,
        },
      },
      offset: 50,
      lineType: 'SmoothCurve',
      strokeWidth: 2,
      strokeDasharray: 'none',
      stroke: '#4e83fd',
    },
    attrs: {
      coordinate: {
        x: 499.5,
        y: 346.74139342821906,
      },
      size: {
        width: 295,
        height: 55.41953552392698,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: 'LF1PUPKL',
    type: 'ConnectLineSprite',
    props: {
      start: {
        x: 0,
        y: 0,
        port: {
          spriteId: 'XECA64VG',
          id: 'sprite-port__XECA64VG__3',
          index: 3,
          x: 100,
          y: 50,
          arcAngle: 0,
        },
      },
      end: {
        x: 306,
        y: 151.41953552392698,
        port: {
          spriteId: '1R7Z6WXM',
          id: 'sprite-port__1R7Z6WXM__2',
          index: 2,
          x: 0,
          y: 50,
          arcAngle: 180,
        },
      },
      offset: 50,
      lineType: 'SmoothCurve',
      strokeWidth: 2,
      strokeDasharray: 'none',
      stroke: '#4e83fd',
    },
    attrs: {
      coordinate: {
        x: 499.5,
        y: 346.74139342821906,
      },
      size: {
        width: 306,
        height: 151.41953552392698,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: '8RDSM76H',
    type: 'ConnectLineSprite',
    props: {
      start: {
        x: 0,
        y: 0,
        port: {
          spriteId: 'XECA64VG',
          id: 'sprite-port__XECA64VG__3',
          index: 3,
          x: 100,
          y: 50,
          arcAngle: 0,
        },
      },
      end: {
        x: 249,
        y: 248.41953552392698,
        port: {
          spriteId: 'UNDKTWCD',
          id: 'sprite-port__UNDKTWCD__2',
          index: 2,
          x: 0,
          y: 50,
          arcAngle: 180,
        },
      },
      offset: 50,
      lineType: 'SmoothCurve',
      strokeWidth: 2,
      strokeDasharray: 'none',
      stroke: '#4e83fd',
    },
    attrs: {
      coordinate: {
        x: 499.5,
        y: 346.74139342821906,
      },
      size: {
        width: 249,
        height: 248.41953552392698,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: 'HVS7Y3QA',
    type: 'ConnectLineSprite',
    props: {
      start: {
        x: 0,
        y: 0,
        port: {
          spriteId: 'XECA64VG',
          id: 'sprite-port__XECA64VG__3',
          index: 3,
          x: 100,
          y: 50,
          arcAngle: 0,
        },
      },
      end: {
        x: 52,
        y: 248.41953552392698,
        port: {
          spriteId: 'NM6PI6JF',
          id: 'sprite-port__NM6PI6JF__2',
          index: 2,
          x: 0,
          y: 50,
          arcAngle: 180,
        },
      },
      offset: 50,
      lineType: 'SmoothCurve',
      strokeWidth: 2,
      strokeDasharray: 'none',
      stroke: '#4e83fd',
    },
    attrs: {
      coordinate: {
        x: 499.5,
        y: 346.74139342821906,
      },
      size: {
        width: 52,
        height: 248.41953552392698,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: 'FGM5O584',
    type: 'ConnectLineSprite',
    props: {
      start: {
        x: 26,
        y: 296.5804644760731,
        port: {
          spriteId: 'XECA64VG',
          id: 'sprite-port__XECA64VG__2',
          index: 2,
          x: 0,
          y: 50,
          arcAngle: 180,
        },
      },
      end: {
        x: 0,
        y: 0,
        port: {
          spriteId: 'MLY1WJU8',
          id: 'sprite-port__MLY1WJU8__3',
          index: 3,
          x: 100,
          y: 50,
          arcAngle: 0,
        },
      },
      offset: 50,
      lineType: 'SmoothCurve',
      strokeWidth: 2,
      strokeDasharray: 'none',
      stroke: '#4e83fd',
    },
    attrs: {
      coordinate: {
        x: 308.5,
        y: 50.16092895214601,
      },
      size: {
        width: 26,
        height: 296.5804644760731,
      },
      angle: 0,
      style: {},
      creating: false,
    },
  },
  {
    id: 'D2SWGORI',
    type: 'ConnectLineSprite',
    props: {
      start: {
        x: 94,
        y: 214.58046447607305,
        port: {
          spriteId: 'XECA64VG',
          id: 'sprite-port__XECA64VG__2',
          index: 2,
          x: 0,
          y: 50,
          arcAngle: 180,
        },
      },
      end: {
        x: 0,
        y: 0,
        port: {
          spriteId: '2N0FLF16',
          id: 'sprite-port__2N0FLF16__3',
          index: 3,
          x: 100,
          y: 50,
          arcAngle: 0,
        },
      },
      offset: 50,
      lineType: 'SmoothCurve',
      strokeWidth: 2,
      strokeDasharray: 'none',
      stroke: '#4e83fd',
    },
    attrs: {
      coordinate: {
        x: 240.5,
        y: 132.160928952146,
      },
      size: {
        width: 94,
        height: 214.58046447607305,
      },
      angle: 0,
      style: {},
      creating: false,
    },
  },
  {
    id: 'HXCTYQFK',
    type: 'ConnectLineSprite',
    props: {
      start: {
        x: 174,
        y: 132.58046447607302,
        port: {
          spriteId: 'XECA64VG',
          id: 'sprite-port__XECA64VG__2',
          index: 2,
          x: 0,
          y: 50,
          arcAngle: 180,
        },
      },
      end: {
        x: 0,
        y: 0,
        port: {
          spriteId: 'U44I0I2W',
          id: 'sprite-port__U44I0I2W__3',
          index: 3,
          x: 100,
          y: 50,
          arcAngle: 0,
        },
      },
      offset: 50,
      lineType: 'SmoothCurve',
      strokeWidth: 2,
      strokeDasharray: 'none',
      stroke: '#4e83fd',
    },
    attrs: {
      coordinate: {
        x: 160.5,
        y: 214.16092895214604,
      },
      size: {
        width: 174,
        height: 132.58046447607302,
      },
      angle: 0,
      style: {},
      creating: false,
    },
  },
  {
    id: 'KKKLJMY9',
    type: 'ConnectLineSprite',
    props: {
      start: {
        x: 173,
        y: 44.5,
        port: {
          spriteId: 'XECA64VG',
          id: 'sprite-port__XECA64VG__2',
          index: 2,
          x: 0,
          y: 50,
          arcAngle: 180,
        },
      },
      end: {
        x: 0,
        y: 0,
        port: {
          spriteId: 'RG4ISEB0',
          id: 'sprite-port__RG4ISEB0__3',
          index: 3,
          x: 100,
          y: 50,
          arcAngle: 0,
        },
      },
      offset: 50,
      lineType: 'SmoothCurve',
      strokeWidth: 2,
      strokeDasharray: 'none',
      stroke: '#4e83fd',
    },
    attrs: {
      coordinate: {
        x: 161.5,
        y: 302.24139342821906,
      },
      size: {
        width: 173,
        height: 44.5,
      },
      angle: 0,
      style: {},
      creating: false,
    },
  },
  {
    id: 'Q707VPBT',
    type: 'RectRoundSprite',
    props: {
      borderRadius: 30,
      stroke: '#9d9d9d',
      strokeWidth: 2,
      content: '<p>节点13<br/></p>',
    },
    attrs: {
      coordinate: {
        x: 24.5,
        y: 349.16092895214604,
      },
      size: {
        width: 136,
        height: 53,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: 'DGVD9ZYN',
    type: 'RectRoundSprite',
    props: {
      borderRadius: 30,
      stroke: '#9d9d9d',
      strokeWidth: 2,
      content: '<p>节点12<br/></p>',
    },
    attrs: {
      coordinate: {
        x: 24.5,
        y: 422.16092895214604,
      },
      size: {
        width: 136,
        height: 53,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: 'XJJM35JW',
    type: 'RectRoundSprite',
    props: {
      borderRadius: 30,
      stroke: '#9d9d9d',
      strokeWidth: 2,
      content: '<p>节点11<br/></p>',
    },
    attrs: {
      coordinate: {
        x: 104.5,
        y: 498.16092895214604,
      },
      size: {
        width: 136,
        height: 53,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: '7C8UOVGN',
    type: 'RectRoundSprite',
    props: {
      borderRadius: 30,
      stroke: '#9d9d9d',
      strokeWidth: 2,
      content: '<p>节点10<br/></p>',
    },
    attrs: {
      coordinate: {
        x: 173.5,
        y: 568.660928952146,
      },
      size: {
        width: 136,
        height: 53,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: 'OWKT5HBC',
    type: 'ConnectLineSprite',
    props: {
      start: {
        x: 174,
        y: 0,
        port: {
          spriteId: 'XECA64VG',
          id: 'sprite-port__XECA64VG__2',
          index: 2,
          x: 0,
          y: 50,
          arcAngle: 180,
        },
      },
      end: {
        x: 0,
        y: 28.91953552392698,
        port: {
          spriteId: 'Q707VPBT',
          id: 'sprite-port__Q707VPBT__3',
          index: 3,
          x: 100,
          y: 50,
          arcAngle: 0,
        },
      },
      offset: 50,
      lineType: 'SmoothCurve',
      strokeWidth: 2,
      strokeDasharray: 'none',
      stroke: '#4e83fd',
    },
    attrs: {
      coordinate: {
        x: 160.5,
        y: 346.74139342821906,
      },
      size: {
        width: 174,
        height: 28.91953552392698,
      },
      angle: 0,
      style: {},
      creating: false,
    },
  },
  {
    id: 'K3XSC66I',
    type: 'ConnectLineSprite',
    props: {
      start: {
        x: 174,
        y: 0,
        port: {
          spriteId: 'XECA64VG',
          id: 'sprite-port__XECA64VG__2',
          index: 2,
          x: 0,
          y: 50,
          arcAngle: 180,
        },
      },
      end: {
        x: 0,
        y: 101.91953552392698,
        port: {
          spriteId: 'DGVD9ZYN',
          id: 'sprite-port__DGVD9ZYN__3',
          index: 3,
          x: 100,
          y: 50,
          arcAngle: 0,
        },
      },
      offset: 50,
      lineType: 'SmoothCurve',
      strokeWidth: 2,
      strokeDasharray: 'none',
      stroke: '#4e83fd',
    },
    attrs: {
      coordinate: {
        x: 160.5,
        y: 346.74139342821906,
      },
      size: {
        width: 174,
        height: 101.91953552392698,
      },
      angle: 0,
      style: {},
      creating: false,
    },
  },
  {
    id: 'GX1EOAHR',
    type: 'ConnectLineSprite',
    props: {
      start: {
        x: 94,
        y: 0,
        port: {
          spriteId: 'XECA64VG',
          id: 'sprite-port__XECA64VG__2',
          index: 2,
          x: 0,
          y: 50,
          arcAngle: 180,
        },
      },
      end: {
        x: 0,
        y: 177.91953552392698,
        port: {
          spriteId: 'XJJM35JW',
          id: 'sprite-port__XJJM35JW__3',
          index: 3,
          x: 100,
          y: 50,
          arcAngle: 0,
        },
      },
      offset: 50,
      lineType: 'SmoothCurve',
      strokeWidth: 2,
      strokeDasharray: 'none',
      stroke: '#4e83fd',
    },
    attrs: {
      coordinate: {
        x: 240.5,
        y: 346.74139342821906,
      },
      size: {
        width: 94,
        height: 177.91953552392698,
      },
      angle: 0,
      style: {},
      creating: false,
    },
  },
  {
    id: 'IYLZVISR',
    type: 'ConnectLineSprite',
    props: {
      start: {
        x: 25,
        y: 0,
        port: {
          spriteId: 'XECA64VG',
          id: 'sprite-port__XECA64VG__2',
          index: 2,
          x: 0,
          y: 50,
          arcAngle: 180,
        },
      },
      end: {
        x: 0,
        y: 248.41953552392698,
        port: {
          spriteId: '7C8UOVGN',
          id: 'sprite-port__7C8UOVGN__3',
          index: 3,
          x: 100,
          y: 50,
          arcAngle: 0,
        },
      },
      offset: 50,
      lineType: 'SmoothCurve',
      strokeWidth: 2,
      strokeDasharray: 'none',
      stroke: '#4e83fd',
    },
    attrs: {
      coordinate: {
        x: 309.5,
        y: 346.74139342821906,
      },
      size: {
        width: 25,
        height: 248.41953552392698,
      },
      angle: 0,
      style: {},
      creating: false,
    },
  },
  {
    id: '4G4QRHE7',
    type: 'RectRoundSprite',
    props: {
      borderRadius: 30,
      stroke: '#9d9d9d',
      strokeWidth: 2,
      content: '<p>节点1</p>',
    },
    attrs: {
      coordinate: {
        x: 521,
        y: 17.66092895214601,
      },
      size: {
        width: 136,
        height: 53,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
  {
    id: 'XECA64VG',
    type: 'RectRoundSprite',
    props: {
      borderRadius: 15.714285714285714,
      fill: '#3370ff',
      strokeWidth: 0,
      content: '<p><font color="#ffffff" size="5">复杂脑图</font></p>',
    },
    attrs: {
      coordinate: {
        x: 334.5,
        y: 316.24139342821906,
      },
      size: {
        width: 165,
        height: 61,
      },
      angle: 0,
      style: {},
      creating: false,
      editing: false,
    },
  },
];
