export const fontFamily = [
  '默认字体',
  '微软雅黑',
  '宋体',
  '黑体',
  '冬青黑简体中文',
  '苹方',
  '华文宋体',
  '华文仿宋',
  '华文楷体',
  'Arial',
  'Times New Roman',
  'Calibri',
  'Comic Sans MS',
  'Courier New',
  'Georgia',
  'Microsoft Uighur',
  'Impact',
  'Trebuchet MS',
  'Verdana',
  'Al Bayan',
  'Al Nile',
  'Al Tarikh',
  'American Typewriter',
  'Andale Mono',
  'Arial Black',
  'Arial Hebrew',
  'Arial Hebrew Scholar',
  'Arial Narrow',
  'Arial Rounded MT Bold',
  'Arial Unicode MS',
  'Athelas',
  'Avenir',
  'Avenir Next',
  'Avenir Next Condensed',
  'Ayuthaya',
  'Baghdad',
  'Bangla MN',
  'Bangla Sangam MN',
  'Baskerville',
  'Beirut',
  'Big Caslon',
  'Bodoni',
  // 'Bodoni 72 Oldstyle',
  // 'Bodoni 72 Smallcaps',
  // 'Bodoni Ornaments',
  // 'Bradley Hand',
  // 'Brush Script MT',
  'Chalkboard',
  'Chalkboard SE',
  'Chalkduster',
  'Charter',
  'Cochin',
  'Copperplate',
  'Corsiva Hebrew',
  'Courier',
  'Damascus',
  'DecoType Naskh',
  'Devanagari MT',
  'Devanagari Sangam MN',
  'Didot',
  'DIN Alternate',
  'DIN Condensed',
  'Diwan Kufi',
  'Diwan Thuluth',
  'Euphemia UCAS',
  'Farah',
  'Farisi',
  'Futura',
  'GB18030 Bitmap',
  'Geeza Pro',
  'Geneva',
  'Gill Sans',
  'Gujarati MT',
  'Gujarati Sangam MN',
  'Gurmukhi MN',
  'Gurmukhi MT',
  'Gurmukhi Sangam MN',
  'Hei',
  'Helvetica',
  'Helvetica Neue',
  'Herculanum',
  'Hiragino Kaku Gothic Pro',
  'Hiragino Kaku Gothic ProN',
  'Hiragino Kaku Gothic Std',
  'Hiragino Kaku Gothic StdN',
  'Hiragino Maru Gothic Pro',
  'Hiragino Maru Gothic ProN',
  'Hiragino Mincho Pro',
  'Hiragino Mincho ProN',
  'Hiragino Sans',
  'Hoefler Text',
  'InaiMathi',
  'Iowan Old Style',
  'ITF Devanagari',
  'ITF Devanagari Marathi',
  'Kai',
  'Kailasa',
  'Kannada MN',
  'Kannada Sangam MN',
  'Kefa',
  'Khmer MN',
  'Khmer Sangam MN',
  'Kohinoor Bangla',
  'Kohinoor Devanagari',
  'Kohinoor Telugu',
  'Kokonor',
  'Krungthep',
  'KufiStandardGK',
  'Lao MN',
  'Lao Sangam MN',
  'Lucida Grande',
  'Luminari',
  'Malayalam MN',
  'Malayalam Sangam MN',
  'Marion',
  'Marker Felt',
  'Menlo',
  'Microsoft Sans Serif',
  'Mishafi',
  'Mishafi Gold',
  'Monaco',
  'Mshtakan',
  'Muna',
  'Myanmar MN',
  'Myanmar Sangam MN',
  'Nadeem',
  'New Peninim MT',
  'Noteworthy',
  'Noto Nastaliq Urdu',
  'Optima',
  'Oriya MN',
  'Oriya Sangam MN',
  'Palatino',
  'Papyrus',
  'Phosphate',
  'Plantagenet Cherokee',
  'PT Mono',
  'PT Sans',
  'PT Sans Caption',
  'PT Sans Narrow',
  'PT Serif',
  'PT Serif Caption',
  'Raanana',
  'Sana',
  'Sathu',
  'Savoye LET',
  'Seravek',
  'Shree Devanagari',
  'SignPainter',
  'Silom',
  'Sinhala MN',
  'Sinhala Sangam MN',
  'Skia',
  'Snell Roundhand',
  // 'STIXGeneral',
  // 'STIXIntegralsD',
  // 'STIXIntegralsSm',
  // 'STIXIntegralsUp',
  // 'STIXIntegralsUpD',
  // 'STIXIntegralsUpSm',
  // 'STIXNonUnicode',
  // 'STIXSizeFiveSym',
  // 'STIXSizeFourSym',
  // 'STIXSizeOneSym',
  // 'STIXSizeThreeSym',
  // 'STIXSizeTwoSym',
  // 'STIXVariants',
  'Sukhumvit Set',
  'Superclarendon',
  'Symbol',
  'Tahoma',
  'Tamil MN',
  'Tamil Sangam MN',
  'Telugu MN',
  'Telugu Sangam MN',
  'Thonburi',
  'Times',
  'Trattatello',
  'Waseem',
  // 'Webdings',
  // 'Wingdings',
  // 'Zapf Dingbats',
  // 'Zapfino',
  'Apple Braille',
  'Apple Chancery',
  'Apple Color Emoji',
  'Apple SD Gothic Neo',
  'Apple Symbols',
  'AppleGothic',
  'AppleMyungjo',
];

export const colors = [
  '#1E1E1E',
  '#F43A2E',
  '#FF9900',
  '#FFD300',
  '#0ED982',
  '#16ECFA',
  '#109BFF',
  '#A245FF',

  '#FFFFFF',
  '#FFEAE9',
  '#FFF6DB',
  '#FCF8CD',
  '#E2FADB',
  '#D1FAFF',
  '#DEF0FF',
  '#F2E7FF',

  '#DBDCE0',
  '#FDC5BF',
  '#FFE6B9',
  '#FEF5A1',
  '#C3F1BC',
  '#8CF4FF',
  '#B6DDFF',
  '#CEADFA',

  '#AAAFB7',
  '#DD8078',
  '#F0C47B',
  '#EFE16E',
  '#84DB92',
  '#4BD8EA',
  '#62A6E7',
  '#9D75D1',

  '#5F6369',
  '#A80F0F',
  '#A96B26',
  '#CFC049',
  '#57AD74',
  '#00A7C4',
  '#3E81CB',
  '#7E44CB',
];
